<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Saucebase — Setup</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700&display=swap" rel="stylesheet">

    <script>
        if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
            document.documentElement.classList.add('dark');
        }
    </script>
    <script src="https://unpkg.com/@tailwindcss/browser@4"></script>
    <style type="text/tailwindcss">
        @custom-variant dark (&:is(.dark *));
    </style>

    <style>
        {!! file_get_contents(resource_path('css/theme.css')) !!}

        /* --color-* aliases (compiled by @theme inline in the real app, manual here) */
        :root {
            --color-background: var(--background);
            --color-foreground: var(--foreground);
            --color-card: var(--card);
            --color-card-foreground: var(--card-foreground);
            --color-primary: var(--primary);
            --color-secondary: var(--secondary);
            --color-muted: var(--muted);
            --color-muted-foreground: var(--muted-foreground);
            --color-border: var(--border);
            --color-white: #ffffff;
            --vue-color: #42b883;
            --react-color: #0ea5e9;
        }

        {!! file_get_contents(resource_path('css/saucebase.css')) !!}

        body {
            font-family: 'Outfit', sans-serif;
            background-color: var(--background);
            color: var(--foreground);
            min-height: 100vh;
            transition: background-color 0.5s ease;
        }
        body.fw-selected {
            background-color: color-mix(in oklch, var(--fw-color) 8%, var(--background));
        }
        .bg-pattern { transition: opacity 0.5s ease; }
        body.fw-selected .bg-pattern { opacity: 0.7; }

        .framework-grid:has([data-card]:hover) [data-card] { opacity: 0.4; }
        .framework-grid:has([data-card]:hover) [data-card]:hover { opacity: 1 !important; }
        .framework-grid:has(.card-drop.selected) [data-card]:not(:has(.card-drop.selected)) { opacity: 0.4; }

        /* Card body shadow — mirrors ModuleCard exactly */
        .card-face {
            background-color: var(--card);
            box-shadow: -1px 1px 0 0 color-mix(in oklch, var(--color-white) 80%, black);
            transition: box-shadow 200ms, transform 200ms, translate 200ms;
        }
        .dark .card-face {
            box-shadow: -2px 2px 0 0 color-mix(in oklch, var(--color-muted) 90%, black);
        }
        .group\/card:hover .card-face {
            box-shadow: -5px 5px 0 0 color-mix(in oklch, color-mix(in oklch, var(--mod-color) 85%, black) 70%, transparent);
        }

        /* Icon circle shadow */
        .card-icon {
            box-shadow: -2px 2px 0 0 color-mix(in oklch, var(--mod-color) 85%, black);
            transition: box-shadow 200ms, transform 200ms, translate 200ms;
        }
        .group\/card:hover .card-icon {
            box-shadow: -5px 5px 0 0 color-mix(in oklch, var(--mod-color) 85%, black);
        }

        /* Theme color utilities not generated by CDN */
        .text-foreground { color: var(--foreground); }
        .text-muted-foreground { color: var(--muted-foreground); }
        .bg-card { background-color: var(--card); }

        @keyframes pill-in {
            from { opacity: 0; transform: translateY(10px); }
            to   { opacity: 1; transform: translateY(0); }
        }
        @keyframes sb-cursor-blink {
            0%, 49% { opacity: 1; }
            50%, 100% { opacity: 0; }
        }
        #command-section { opacity: 0; }
        #command-section.pill-visible { animation: pill-in 0.35s ease-out forwards; }
        #cmd-cursor {
            color: var(--pill-ring, #4ade80);
            animation: sb-cursor-blink 0.75s ease-in-out infinite;
        }

        .card-drop.selected .card-face {
            transform: translateX(6px) translateY(-6px);
            box-shadow: -5px 5px 0 0 color-mix(in oklch, color-mix(in oklch, var(--mod-color) 85%, black) 70%, transparent);
        }
        .card-drop.selected .card-icon {
            transform: translateX(6px) translateY(-6px);
            box-shadow: -5px 5px 0 0 color-mix(in oklch, var(--mod-color) 85%, black);
        }
    </style>
</head>

<body>
    <div class="relative min-h-screen overflow-hidden flex items-center justify-center p-8">

        <!-- Content -->
        <div class="relative z-10 w-full max-w-3xl mx-auto pb-10">

            <!-- Heading -->
            <div class="pb-4 text-center">
                <h1 class="text-center text-5xl font-bold md:text-6xl"
                    style="color: var(--primary); text-shadow: 0 4px 25px color-mix(in oklch, var(--primary) 15%, var(--background))">
                    The kitchen is set
                </h1>
                <h2 class="mt-1 text-center text-5xl font-bold md:text-6xl"
                    style="color: var(--secondary)">
                    Pick your flavor
                </h2>
                <p class="mt-3 text-center text-xl tracking-normal md:text-2xl"
                    style="color: var(--muted-foreground)">
                    The base handles everything else
                </p>
            </div>

            <!-- Framework cards -->
            <div class="framework-grid relative z-10 mx-auto grid max-w-xl grid-cols-2 items-stretch gap-12 px-6 pt-8 pb-8">

                <!-- Vue card -->
                <div data-card id="card-vue" onclick="selectFramework('vue')"
                    class="select-none relative flex flex-col cursor-pointer transition-opacity duration-200"
                    style="--mod-color: var(--vue-color); --card-delay: 400ms; transform: rotate(-5deg) skewX(10deg)">

                    <div class="stripe stripe-appear absolute inset-x-2 top-9 bottom-0 w-full -translate-x-5 translate-y-2.5 rounded-xl opacity-90"
                        style="animation-delay: calc(var(--card-delay) + 50ms)"></div>

                    <div id="drop-vue" class="card-drop group/card relative flex flex-1 flex-col pt-6" style="animation-delay: var(--card-delay)">
                        <div class="relative flex-1">
                            <div id="body-vue"
                                class="card-face bg-card relative z-10 flex h-full flex-col gap-2 rounded-xl px-1 pt-12 pb-8 text-left transition-all duration-200 group-hover/card:translate-x-1.5 group-hover/card:-translate-y-1.5">

                                <!-- Floating icon -->
                                <div class="card-icon bounce absolute -top-2 left-1/2 z-10 -ml-6 flex size-16.75 shrink-0 items-center justify-center rounded-full transition-all duration-200 group-hover/card:translate-x-1.5 group-hover/card:-translate-y-1.5"
                                    style="background: var(--vue-color); animation-delay: calc(var(--card-delay) + 280ms)">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="absolute size-10 text-black/10 transition-all duration-200 group-hover/card:text-black/30 group-hover/card:blur-[1.5px]" aria-hidden="true">
                                        <path d="m12 12.765 5.592-9.437h-3.276L12 7.33v.002L9.688 3.328h-3.28z"/><path d="M18.461 3.332 12 14.235 5.539 3.332H1.992L12 20.672l10.008-17.34z"/>
                                    </svg>
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="bounce absolute size-10 translate-x-0.5 -translate-y-0.5 text-white transition-transform duration-200 group-hover/card:translate-x-1 group-hover/card:-translate-y-1.5" aria-hidden="true"
                                        style="animation-delay: calc(var(--card-delay) + 280ms)">
                                        <path d="m12 12.765 5.592-9.437h-3.276L12 7.33v.002L9.688 3.328h-3.28z"/><path d="M18.461 3.332 12 14.235 5.539 3.332H1.992L12 20.672l10.008-17.34z"/>
                                    </svg>
                                </div>

                                <!-- Stripe ring around icon -->
                                <div class="stripe absolute top-0 left-1/2 -ml-8.5 size-16.75 rounded-full"></div>

                                <span class="text-foreground mt-11 text-center text-xl leading-tight font-semibold">Vue</span>
                                <p class="text-muted-foreground line-clamp-3 text-center text-sm leading-snug">
                                    The progressive framework
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- React card -->
                <div data-card id="card-react" onclick="selectFramework('react')"
                    class="select-none relative flex flex-col cursor-pointer transition-opacity duration-200"
                    style="--mod-color: var(--react-color); --card-delay: 550ms; transform: rotate(-5deg) skewX(10deg)">

                    <div class="stripe stripe-appear absolute inset-x-2 top-9 bottom-0 w-full -translate-x-5 translate-y-2.5 rounded-xl opacity-90"
                        style="animation-delay: calc(var(--card-delay) + 50ms)"></div>

                    <div id="drop-react" class="card-drop group/card relative flex flex-1 flex-col pt-6" style="animation-delay: var(--card-delay)">
                        <div class="relative flex-1">
                            <div id="body-react"
                                class="card-face bg-card relative z-10 flex h-full flex-col gap-2 rounded-xl px-1 pt-12 pb-8 text-left transition-all duration-200 group-hover/card:translate-x-1.5 group-hover/card:-translate-y-1.5">

                                <!-- Floating icon -->
                                <div class="card-icon bounce absolute -top-2 left-1/2 z-10 -ml-6 flex size-16.75 shrink-0 items-center justify-center rounded-full transition-all duration-200 group-hover/card:translate-x-1.5 group-hover/card:-translate-y-1.5"
                                    style="background: var(--react-color); animation-delay: calc(var(--card-delay) + 280ms)">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="absolute size-10 text-black/10 transition-all duration-200 group-hover/card:text-black/30 group-hover/card:blur-[1.5px]" aria-hidden="true">
                                        <path d="M12 9.46a1.785 1.785 0 1 0 0 3.57 1.785 1.785 0 1 0 0-3.57M7.002 14.794l-.395-.101c-2.934-.741-4.617-2.001-4.617-3.452S3.674 8.53 6.607 7.789l.395-.1.111.391a19.5 19.5 0 0 0 1.136 2.983l.085.178-.085.178c-.46.963-.841 1.961-1.136 2.985zm-.577-6.095c-2.229.628-3.598 1.586-3.598 2.542 0 .954 1.368 1.913 3.598 2.54q.41-1.304.985-2.54a20 20 0 0 1-.985-2.542m10.572 6.095-.11-.392a19.6 19.6 0 0 0-1.137-2.984l-.085-.177.085-.179c.46-.961.839-1.96 1.137-2.984l.11-.39.395.1c2.935.741 4.617 2 4.617 3.453s-1.683 2.711-4.617 3.452zm-.41-3.553c.4.866.733 1.718.987 2.54 2.23-.627 3.599-1.586 3.599-2.54 0-.956-1.368-1.913-3.599-2.542a21 21 0 0 1-.987 2.542"/><path d="m6.419 8.695-.11-.39c-.826-2.908-.576-4.991.687-5.717 1.235-.715 3.222.13 5.303 2.265l.284.292-.284.291a20 20 0 0 0-2.02 2.474l-.113.162-.196.016a19.7 19.7 0 0 0-3.157.509zm1.582-5.529q-.337 0-.589.145c-.828.477-.974 2.138-.404 4.38q1.337-.297 2.696-.417a21 21 0 0 1 1.713-2.123c-1.303-1.267-2.533-1.985-3.416-1.985m7.997 16.984c-1.188 0-2.714-.896-4.298-2.522l-.283-.291.283-.29a20 20 0 0 0 2.021-2.477l.112-.16.194-.019a19.5 19.5 0 0 0 3.158-.507l.395-.1.111.391c.822 2.906.573 4.992-.688 5.718a2 2 0 0 1-1.005.257m-3.415-2.82c1.302 1.267 2.533 1.986 3.415 1.986q.339-.001.589-.145c.829-.478.976-2.142.404-4.384q-1.335.299-2.698.419a20.5 20.5 0 0 1-1.71 2.124"/><path d="m17.58 8.695-.395-.099a19.5 19.5 0 0 0-3.158-.509l-.194-.017-.112-.162A19.6 19.6 0 0 0 11.7 5.434l-.283-.291.283-.29c2.08-2.134 4.066-2.979 5.303-2.265 1.262.727 1.513 2.81.688 5.717zm-3.287-1.421c.954.085 1.858.228 2.698.417.571-2.242.425-3.903-.404-4.381-.824-.477-2.375.253-4.004 1.841q.926 1.005 1.71 2.123M8.001 20.15a2 2 0 0 1-1.005-.257c-1.263-.726-1.513-2.811-.688-5.718l.108-.391.395.1c.964.243 2.026.414 3.158.507l.194.019.113.16c.604.878 1.28 1.707 2.02 2.477l.284.29-.284.291c-1.583 1.627-3.109 2.522-4.295 2.522m-.993-5.362c-.57 2.242-.424 3.906.404 4.384.825.47 2.371-.255 4.005-1.842a21 21 0 0 1-1.713-2.123 21 21 0 0 1-2.696-.419"/><path d="M12 15.313c-.687 0-1.392-.029-2.1-.088l-.196-.017-.113-.162a26 26 0 0 1-1.126-1.769 26 26 0 0 1-.971-1.859l-.084-.177.084-.179q.448-.948.971-1.858c.347-.596.726-1.192 1.126-1.77l.113-.16.196-.018a25 25 0 0 1 4.198 0l.194.019.113.16a25 25 0 0 1 2.1 3.628l.083.179-.083.177a25 25 0 0 1-2.1 3.628l-.113.162-.194.017c-.706.057-1.412.087-2.098.087m-1.834-.904c1.235.093 2.433.093 3.667 0a24.5 24.5 0 0 0 1.832-3.168 24 24 0 0 0-1.832-3.168 24 24 0 0 0-3.667 0 24 24 0 0 0-1.832 3.168 25 25 0 0 0 1.832 3.168"/>
                                    </svg>
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="bounce absolute size-10 translate-x-0.5 -translate-y-0.5 text-white transition-transform duration-200 group-hover/card:translate-x-1 group-hover/card:-translate-y-1.5" aria-hidden="true"
                                        style="animation-delay: calc(var(--card-delay) + 280ms)">
                                        <path d="M12 9.46a1.785 1.785 0 1 0 0 3.57 1.785 1.785 0 1 0 0-3.57M7.002 14.794l-.395-.101c-2.934-.741-4.617-2.001-4.617-3.452S3.674 8.53 6.607 7.789l.395-.1.111.391a19.5 19.5 0 0 0 1.136 2.983l.085.178-.085.178c-.46.963-.841 1.961-1.136 2.985zm-.577-6.095c-2.229.628-3.598 1.586-3.598 2.542 0 .954 1.368 1.913 3.598 2.54q.41-1.304.985-2.54a20 20 0 0 1-.985-2.542m10.572 6.095-.11-.392a19.6 19.6 0 0 0-1.137-2.984l-.085-.177.085-.179c.46-.961.839-1.96 1.137-2.984l.11-.39.395.1c2.935.741 4.617 2 4.617 3.453s-1.683 2.711-4.617 3.452zm-.41-3.553c.4.866.733 1.718.987 2.54 2.23-.627 3.599-1.586 3.599-2.54 0-.956-1.368-1.913-3.599-2.542a21 21 0 0 1-.987 2.542"/><path d="m6.419 8.695-.11-.39c-.826-2.908-.576-4.991.687-5.717 1.235-.715 3.222.13 5.303 2.265l.284.292-.284.291a20 20 0 0 0-2.02 2.474l-.113.162-.196.016a19.7 19.7 0 0 0-3.157.509zm1.582-5.529q-.337 0-.589.145c-.828.477-.974 2.138-.404 4.38q1.337-.297 2.696-.417a21 21 0 0 1 1.713-2.123c-1.303-1.267-2.533-1.985-3.416-1.985m7.997 16.984c-1.188 0-2.714-.896-4.298-2.522l-.283-.291.283-.29a20 20 0 0 0 2.021-2.477l.112-.16.194-.019a19.5 19.5 0 0 0 3.158-.507l.395-.1.111.391c.822 2.906.573 4.992-.688 5.718a2 2 0 0 1-1.005.257m-3.415-2.82c1.302 1.267 2.533 1.986 3.415 1.986q.339-.001.589-.145c.829-.478.976-2.142.404-4.384q-1.335.299-2.698.419a20.5 20.5 0 0 1-1.71 2.124"/><path d="m17.58 8.695-.395-.099a19.5 19.5 0 0 0-3.158-.509l-.194-.017-.112-.162A19.6 19.6 0 0 0 11.7 5.434l-.283-.291.283-.29c2.08-2.134 4.066-2.979 5.303-2.265 1.262.727 1.513 2.81.688 5.717zm-3.287-1.421c.954.085 1.858.228 2.698.417.571-2.242.425-3.903-.404-4.381-.824-.477-2.375.253-4.004 1.841q.926 1.005 1.71 2.123M8.001 20.15a2 2 0 0 1-1.005-.257c-1.263-.726-1.513-2.811-.688-5.718l.108-.391.395.1c.964.243 2.026.414 3.158.507l.194.019.113.16c.604.878 1.28 1.707 2.02 2.477l.284.29-.284.291c-1.583 1.627-3.109 2.522-4.295 2.522m-.993-5.362c-.57 2.242-.424 3.906.404 4.384.825.47 2.371-.255 4.005-1.842a21 21 0 0 1-1.713-2.123 21 21 0 0 1-2.696-.419"/><path d="M12 15.313c-.687 0-1.392-.029-2.1-.088l-.196-.017-.113-.162a26 26 0 0 1-1.126-1.769 26 26 0 0 1-.971-1.859l-.084-.177.084-.179q.448-.948.971-1.858c.347-.596.726-1.192 1.126-1.77l.113-.16.196-.018a25 25 0 0 1 4.198 0l.194.019.113.16a25 25 0 0 1 2.1 3.628l.083.179-.083.177a25 25 0 0 1-2.1 3.628l-.113.162-.194.017c-.706.057-1.412.087-2.098.087m-1.834-.904c1.235.093 2.433.093 3.667 0a24.5 24.5 0 0 0 1.832-3.168 24 24 0 0 0-1.832-3.168 24 24 0 0 0-3.667 0 24 24 0 0 0-1.832 3.168 25 25 0 0 0 1.832 3.168"/>
                                    </svg>
                                </div>

                                <!-- Stripe ring around icon -->
                                <div class="stripe absolute top-0 left-1/2 -ml-8.5 size-16.75 rounded-full"></div>

                                <span class="text-foreground mt-11 text-center text-xl leading-tight font-semibold">React</span>
                                <p class="text-muted-foreground line-clamp-3 text-center text-sm leading-snug">
                                    The industry standard
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Command pill -->
            <div id="command-section" style="display: none;" class="mx-auto max-w-lg px-6 pb-4 mt-10">
                <div class="flex items-center gap-3 rounded-full px-5 py-3 shadow-sm" style="background-color: oklch(0.13 0.02 264); outline: 6px solid color-mix(in oklch, var(--pill-ring, oklch(0.28 0.03 264)) 90%, transparent)">
                    <svg xmlns="http://www.w3.org/2000/svg" style="color: oklch(0.55 0.02 264)" class="size-4 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <polyline points="4 17 10 11 4 5"/>
                        <line x1="12" y1="19" x2="20" y2="19"/>
                    </svg>
                    <code id="command-text" class="flex-1 text-sm font-mono" style="color: var(--pill-ring, #4ade80)"></code>
                    <button onclick="copyCommand()" class="cursor-pointer transition-colors shrink-0" style="color: oklch(0.65 0.02 264)" aria-label="Copy command"
                        onmouseover="this.style.color='white'" onmouseout="this.style.color='oklch(0.65 0.02 264)'">
                        <svg id="icon-copy" xmlns="http://www.w3.org/2000/svg" class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                            <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/>
                            <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>
                        </svg>
                        <svg id="icon-check" xmlns="http://www.w3.org/2000/svg" class="size-4 hidden" style="color: #4ade80" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                            <polyline points="20 6 9 17 4 12"/>
                        </svg>
                    </button>
                </div>
            </div>

            <p class="text-center mt-10" style="color: var(--muted-foreground)">
                Need help? See the <a href="https://saucebase-dev.github.io/docs/" style="color: var(--primary)" class="underline hover:opacity-80 transition-opacity">documentation</a>
            </p>
        </div>

        <!-- Background pattern — light -->
        <div class="bg-pattern dark:hidden absolute inset-0 -top-10 -right-20 -bottom-10 -left-20 -z-1 overflow-hidden rotate-[-5deg] skew-x-10"
            style="background-size:24px;background-position:top left;background-image:url('data:image/svg+xml,%3Csvg viewBox=%220 0 32 32%22 fill=%22none%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cg opacity=%22.4%22 fill=%22%23011E32%22 fill-opacity=%22.24%22%3E%3Cpath fill-rule=%22evenodd%22 clip-rule=%22evenodd%22 d=%22M0 .5V6h.5V.5H6V0H0v.5ZM.5 32H0v-6h.5v5.5H6v.5H.5ZM32 0v6h-.5V.5H26V0h6Zm0 31.5V26h-.5v5.5H26v.5h6v-.5Z%22/%3E%3Cpath opacity=%22.6%22 d=%22M19 0v.5h-6V0zM19 31.5v.5h-6v-.5zM32 19h-.5v-6h.5zM.5 19H0v-6h.5z%22/%3E%3C/g%3E%3C/svg%3E');
                    -webkit-mask-image: linear-gradient(to bottom, transparent, black 15%, black 85%, transparent), linear-gradient(to right, transparent, black 15%, black 85%, transparent);
                    -webkit-mask-composite: source-in;
                    mask-image: linear-gradient(to bottom, transparent, black 15%, black 85%, transparent), linear-gradient(to right, transparent, black 15%, black 85%, transparent);
                    mask-composite: intersect;">
        </div>
        <!-- Background pattern — dark -->
        <div class="bg-pattern hidden dark:block absolute inset-0 -top-10 -right-20 -bottom-10 -left-20 -z-1 overflow-hidden rotate-[-5deg] skew-x-10"
            style="background-size:24px;background-position:top left;background-image:url('data:image/svg+xml,%3Csvg viewBox=%220 0 32 32%22 fill=%22none%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cg opacity=%22.5%22 fill=%22%23ffffff%22 fill-opacity=%22.15%22%3E%3Cpath fill-rule=%22evenodd%22 clip-rule=%22evenodd%22 d=%22M0 .5V6h.5V.5H6V0H0v.5ZM.5 32H0v-6h.5v5.5H6v.5H.5ZM32 0v6h-.5V.5H26V0h6Zm0 31.5V26h-.5v5.5H26v.5h6v-.5Z%22/%3E%3Cpath opacity=%22.6%22 d=%22M19 0v.5h-6V0zM19 31.5v.5h-6v-.5zM32 19h-.5v-6h.5zM.5 19H0v-6h.5z%22/%3E%3C/g%3E%3C/svg%3E');
                    -webkit-mask-image: linear-gradient(to bottom, transparent, black 15%, black 85%, transparent), linear-gradient(to right, transparent, black 15%, black 85%, transparent);
                    -webkit-mask-composite: source-in;
                    mask-image: linear-gradient(to bottom, transparent, black 15%, black 85%, transparent), linear-gradient(to right, transparent, black 15%, black 85%, transparent);
                    mask-composite: intersect;">
        </div>
    </div>

    <script>
        const commands = {
            vue: 'php artisan saucebase:stack vue',
            react: 'php artisan saucebase:stack react',
        };
        let currentCommand = '';
        let typingTimer = null;
        let pillShown = false;

        function selectFramework(fw) {
            ['vue', 'react'].forEach(f => {
                document.getElementById('drop-' + f).classList.remove('selected');
            });
            document.getElementById('drop-' + fw).classList.add('selected');
            currentCommand = commands[fw];

            document.body.style.setProperty('--fw-color', 'var(--' + fw + '-color)');
            document.body.classList.add('fw-selected');

            const section = document.getElementById('command-section');
            section.style.setProperty('--pill-ring', 'var(--' + fw + '-color)');
            if (!pillShown) {
                pillShown = true;
                section.style.display = 'block';
                requestAnimationFrame(() => requestAnimationFrame(() => {
                    section.classList.add('pill-visible');
                    setTimeout(() => typeCommand(currentCommand), 200);
                }));
            } else {
                typeCommand(currentCommand);
            }
        }

        function typeCommand(text) {
            if (typingTimer) { clearInterval(typingTimer); typingTimer = null; }
            const el = document.getElementById('command-text');
            el.innerHTML = '<span id="cmd-cursor">_</span>';

            setTimeout(() => {
                let i = 0;
                typingTimer = setInterval(() => {
                    const cursor = '<span id="cmd-cursor">_</span>';
                    el.innerHTML = text.substring(0, i + 1) + cursor;
                    i++;
                    if (i >= text.length) {
                        clearInterval(typingTimer); typingTimer = null;
                        setTimeout(() => { el.innerHTML = text; }, 1200);
                    }
                }, 48);
            }, 500);
        }

        function copyCommand() {
            navigator.clipboard.writeText(currentCommand).then(() => {
                document.getElementById('icon-copy').classList.add('hidden');
                document.getElementById('icon-check').classList.remove('hidden');
                setTimeout(() => {
                    document.getElementById('icon-copy').classList.remove('hidden');
                    document.getElementById('icon-check').classList.add('hidden');
                }, 2000);
            });
        }
    </script>
</body>

</html>
