name: ___Module___ Module Tests

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

permissions:
    contents: read

jobs:
    test:
        uses: sauce-base/saucebase/.github/workflows/test-module.yml@main
        with:
            module: ___Module___
            # dependencies: saucebase/auth  # add space-separated packages if needed
